vse li pravilno
htmlacademy-htmlcss/2379377-sedona-1 pull request #2
Opened 2024-05-09 09:41 UTC by SuxovAleksey

2024-05-09 11:23 UTC, SuxovAleksey commented
hero-блок

2024-05-22 19:59 UTC, summertime-fms commented on catalog.html
> +            <a class="navigetion-link navigation-link-current" href="catalog.html">Гостиницы</a>
Можно не делать ссылку на саму себя у страницы. Атрибут href можно убрать

2024-05-22 19:59 UTC, summertime-fms commented on catalog.html
> +        <img src="" alt="Горы фон">
А если это фон, то почему изображение контентное?)

Вообще, оно больше контентное чем фоновое, да, но в alt лучше записать более подробную инфу. Например Иллюстрация гор седоны.

2024-05-22 19:59 UTC, summertime-fms commented on catalog.html
> +            </a>
Тут вложенность поехала, точнее отступы. Надо поправить. 
И вообще лучше такое кнопками сделать. в тг объясню)

2024-05-22 19:59 UTC, summertime-fms commented on catalog.html
> +              <li>
Снова плохо с отступами. вложенный тег должен на 1 таб (2 пробела) быть правее своего родителя. Сейчас страдает читаемость. Скину в тг расширения в вс код которые помогут это поправить

2024-05-22 19:59 UTC, summertime-fms commented on catalog.html
> +                <button class="button button-activ" type="submit">в избранном</button>
Кнопка ничего не отправляет, это `type="button"`

2024-05-22 19:59 UTC, summertime-fms commented on catalog.html
> +                <img class="hotel-card-stars" src="" alt="звёздочка">
грузить 4 картинки - громоздко. можно оформить списком и на li навесить фоном одну звездочку. будет легко управлять количеством звезд. Но нужен будет скрытый спан с информацией о количестве звезд, а то для людей с ограниченными возможностями эта инфа может потеряться

2024-05-22 19:59 UTC, summertime-fms commented on catalog.html
> +              </li>
почему они все -current?
Только один пункт может быть активный

2024-05-22 19:59 UTC, summertime-fms commented on catalog.html
> +            </section>
что то много отбивочных строк)

2024-05-22 19:59 UTC, summertime-fms commented on catalog.html
> +        <nav class="network">
нав тут лишний, мы же не кладем сюда ссылки внутренние, наоборот тут ссылки на внешние ресурсы

2024-05-22 19:59 UTC, summertime-fms commented on catalog.html
> +          <p class="tel">+7 (812) 812-12-12</p>
обернуть в ссылку с протоколом tel:  надо
будет удобно кликать

2024-05-22 19:59 UTC, summertime-fms commented on catalog.html
> +          <img class="logo-html" src="" alt="Логотип академии HTML">
Оборачиваем в ссылку. ссылка ведет на сайт академии)

2024-05-22 19:59 UTC, summertime-fms commented on index.html
> +      </section>
вложенность

2024-05-22 19:59 UTC, summertime-fms commented on index.html
> +          <img src="" alt="фото улицы в Седоне.">
если делаешь списком то не может тег лежать сам по себе без <li>

2024-05-22 19:59 UTC, summertime-fms commented on index.html
> +      </section>
Можно в одну секцию объединить) первая секция особо не тянет на крупный смысловой блок, а вот все вместе - да

2024-05-27 13:44 UTC, summertime-fms requested changes

2024-05-27 13:44 UTC, summertime-fms commented on catalog.html
> +                </label>
В лейбле должен быть текст помогающий понять что это за инпут. Давай добавим. Скрытый спан можно

2024-05-27 13:44 UTC, summertime-fms commented on catalog.html
> +                <img class="hotel-card-stars" src="" alt="звёздочка">
Писал в тг по этому поводу. делать каждую звездочку через img не очень хорошее решение

2024-06-02 11:22 UTC, merged